#!/bin/bash

ENV=$1

if [ -z $ENV ] ; then
  echo "need to provide environment name"
  exit 1
fi
shift

COMPONENT=$1
echo $COMPONENT >&2

if [ -z $COMPONENT ] ; then
  echo "need to provide component name"
  exit 1
fi
shift

env >&2.

echo $bastion_public >&2.
. ../venv/bin/activate >&2.
env ./scripts/$COMPONENT.sh $ENV > ${OUTPUT_PATH}
result=$?
echo ${result} > ${EXIT_CODE_PATH}

exit $result
