#!/bin/bash

ENV=$1

if [ -z $ENV ] ; then
  echo "need to provide environment name"
  exit 1
fi
shift

COMPONENT=$1
echo $COMPONENT >&2

if [ -z $COMPONENT ] ; then
  echo "need to provide component name"
  exit 1
fi
shift

inventory_file=$(readlink -f inventory)
pushd playbooks/${COMPONENT}
set -a
source ~/.aws/env
set +a
ansible-playbook -i ${inventory_file} ${COMPONENT}.playbook.yml --user root
echo $? > ${EXIT_CODE_PATH}
