#!/bin/bash
var_file=$(readlink -f common.tfvars)

./t laptop-backup bastion destroy -force -var-file $var_file
./t laptop-backup private destroy -force -var-file $var_file
./t laptop-backup repository destroy -force
./t laptop-backup repository-volume destroy -force
./t laptop-backup vault destroy -force -var-file $var_file

./t laptop-backup vault-volume destroy -force
./t laptop-backup services destroy -force
./t laptop-backup elasticsearch destroy -force -var-file $var_file
./t laptop-backup prometheus destroy -force -var-file $var_file
./t laptop-backup dns destroy -force
./t laptop-backup security destroy -force

./t laptop-backup vpc destroy -force -var-file $var_file
./t laptop-backup users destroy -force
