#!/bin/bash

ENV=$1

if [ -z $ENV ] ; then
  echo "need to provide environment name"
  exit 1
fi
shift

COMPONENT=$1

if [ -z $COMPONENT ] ; then
  echo "need to provide component name"
  exit 1
fi
shift

dir=$(pwd)
build_dir=$(readlink -f build)
cd ..
tar -cvzf ${build_dir}/${COMPONENT}.${BUILD_NUMBER}.tgz --exclude .terraform --exclude outputs $(basename ${dir})
