#!/bin/bash

ENV=$1

if [ -z $ENV ] ; then
  echo "need to provide environment name"
  exit 1
fi
shift

COMPONENT=$1

if [ -z $COMPONENT ] ; then
  echo "need to provide component name"
  exit 1
fi
shift

pwd

set -a
source ~/.aws/env
set +a
export HOME=/home/$(whoami)
COMMON=$(readlink -f common.tfvars)

if [ -f inputs/${COMPONENT} ] ; then
  while read line ; do
    echo "Passing ${line} to Terraform"
    export TF_VAR_${line}=${!line}
  done < inputs/${COMPONENT}
fi

which terraform
./t $ENV $COMPONENT version
echo "Running apply"
./t $ENV $COMPONENT apply -var-file $COMMON
exit_code=$?
echo ${exit_code} > ${EXIT_CODE_PATH}
./t $ENV $COMPONENT output
exit $exit_code
