#!/bin/bash

ENV=$1

if [ -z $ENV ] ; then
  echo "need to provide environment name"
  exit 1
fi
shift

COMPONENT=$1
echo $COMPONENT >&2

if [ -z $COMPONENT ] ; then
  echo "need to provide component name"
  exit 1
fi
shift

pushd ${COMPONENT}

gradle build
exit_code=$?

echo ${exit_code} > ${EXIT_CODE_PATH}
echo "{}" > ${OUTPUT_PATH}

tar -cf ${ARTIFACT_PATH} build
