#!/bin/bash

ENV=$1

if [ -z $ENV ] ; then
  echo "need to provide environment name"
  exit 1
fi
shift

COMPONENT=$1
echo $COMPONENT >&2

if [ -z $COMPONENT ] ; then
  echo "need to provide component name"
  exit 1
fi
shift

if [ ! -d tests/${COMPONENT} ] ; then
  echo "No tests configured for component ${COMPONENT}"
  echo 0 > ${EXIT_CODE_PATH}
  echo "{}" > ${OUTPUT_PATH}
  exit 0
fi


set -a
source ~/.aws/env
set +a

export HOME=/home/$USER

for worker in ${workers} ; do
  command="inspec exec tests/${COMPONENT} --chef-license accept -t ssh://ubuntu@${worker} --key-files ~/.ssh/${key_name}"
  echo $command
  ${command}
  exit_code=$?
  if [ ${exit_code} -ne 0 ] ; then
    echo ${exit_code} > ${EXIT_CODE_PATH}
    break
  else
    echo ${exit_code} > ${EXIT_CODE_PATH}
  fi
done
echo "{}" > ${OUTPUT_PATH}
